apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: mem-example
spec:
  containers:
  - name: grafana
    image: grafana/grafana
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"